name: CI

on:
  push:
    branches:
      - master
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:
    - opened # opened
    - reopened # reopened
    - synchronize # new commit(s) pushed
    - ready_for_review # for draft support

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  linux-test:
    name: Linux (ubuntu) test
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libasound2-dev
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components:
            - clippy
            - rustfmt
      - uses: actions-rs/cargo@v1
        name: Cargo Test
        with:
          command: test
      - uses: actions-rs/cargo@v1
        name: Cargo Format
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/clippy-check@v1
        name: Cargo Clippy
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -D warnings
