[package]
name = "spotify_player"
version = "0.1.0"
authors = ["Thang Pham <phamducthang1234@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.42"
clap = "2.33.3"
config_parser2 = "0.1.2"
crossterm = { version = "0.20.0", features = ["event-stream"] }
dirs-next = "2.0.0"
env_logger = "0.9.0"
log = "0.4.14"
reqwest = { version = "0.10.0", features = ["json"] }
rspotify = "0.10.0"
serde = { version = "1.0.126", features = ["derive"] }
tokio = { version = "0.2", features = ["full"] }
toml = "0.5.8"
tui = { version = "0.15.0", default-features = false, features = ["crossterm"] }
unicode-width = "0.1.8"
